name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm run all

      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          file_pattern: dist/**

      - run: node -p "'version=' + require('./package.json').version" >> $GITHUB_OUTPUT
        id: version

      - uses: ./
        id: parsedVersion
        with:
          version: ${{ steps.version.outputs.version }}

      - run: git tag --force v${{ steps.parsedVersion.outputs.major }}.${{ steps.parsedVersion.outputs.minor }}.${{ steps.parsedVersion.outputs.patch }}
      - run: git tag --force v${{ steps.parsedVersion.outputs.major }}.${{ steps.parsedVersion.outputs.minor }}
      - run: git tag --force v${{ steps.parsedVersion.outputs.major }}
      - run: git tag --force 'latest'

      - run: git push --force --tags origin

      - uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.parsedVersion.outputs.major }}.${{ steps.parsedVersion.outputs.minor }}.${{ steps.parsedVersion.outputs.patch }}
          tag_name: v${{ steps.parsedVersion.outputs.major }}.${{ steps.parsedVersion.outputs.minor }}.${{ steps.parsedVersion.outputs.patch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
